louvre:
    resource: "@LouvreBundle/Controller/"
    type:     annotation
    prefix:   /

EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode