<?php

namespace LouvreBundle\Repository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOne($age)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.ageMin <= :age')
            ->andWhere('a.ageMax > :age')
            ->setParameter('age', $age)
        ;
        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
