services:
#    louvre.example:
#        class: LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    louvre.orderserial:
        class: LouvreBundle\Utils\OrderSerial
        arguments:
            - "@doctrine.orm.entity_manager"

    louvre.ticketprice:
        class: LouvreBundle\Utils\TicketPrice
        arguments:
            - "@doctrine.orm.entity_manager"

    louvre.ordermail:
        class: LouvreBundle\Utils\OrderMail